feat: add generic arrow banner
Arrow-air/tf-github pull request #120
Opened 2023-04-17 22:05 UTC by ServiceDog

2023-04-17 23:28 UTC, GoodluckH submitted a review, later dismissed

2023-04-18 09:48 UTC, owlot requested changes
I removed it because it has the old colors.
We'll need a new version with the latest branding.

2023-05-11 23:55 UTC, GoodluckH approved these changes

2023-05-24 18:10 UTC, owlot commented
New branded version has been added in PR #128

2023-05-24 18:10 UTC, closed without merging