Add se-services repo to TF
Arrow-air/tf-github pull request #21
Opened 2022-08-26 01:15 UTC by ServiceDog

2022-08-26 15:05 UTC, GoodluckH approved these changes

2022-08-29 08:35 UTC, owlot requested changes
Looks good, but the `se-services` repo already seems to exist.

https://github.com/Arrow-air/se-services

We will need to remove it before merging and applying this change.

2022-08-29 15:49 UTC, ServiceDog commented
> Looks good, but the `se-services` repo already seems to exist.
> 
> https://github.com/Arrow-air/se-services
> 
> We will need to remove it before merging and applying this change.

I don't have the permissions to delete [se-services](https://github.com/Arrow-air/se-services), would @owlot or @thomasgarrison go ahead? I have the files locally

2022-08-30 10:03 UTC, owlot approved these changes

2022-08-30 15:05 UTC, merged