Update Makefile.tftpl
Arrow-air/tf-github pull request #39
Opened 2022-09-29 18:41 UTC by ServiceDog

2022-09-29 20:27 UTC, owlot requested changes
line 181 of the Makefile.tftpl file still contains whitespace. Can you fix those?
I'm not sure why they are not fixed by visual code as the .editorconfig file should catch these

2022-09-29 20:41 UTC, ServiceDog commented
> line 181 of the Makefile.tftpl file still contains whitespaces. Can you fix those? I'm not sure why they are not fixed by visual code as the .editorconfig file should catch these

Fixed, if I interpreted correctly: https://github.com/Arrow-air/tf-github/pull/39/commits/753053e7e3db2f5ebfcf3ef82354e23aba29787e

2022-09-29 21:14 UTC, owlot approved these changes

2022-10-03 17:55 UTC, owlot commented
Has been implemented as part of https://github.com/Arrow-air/tf-github/pull/40

2022-10-03 17:55 UTC, closed without merging