Ignore target folder
Arrow-air/tf-github pull request #43
Opened 2022-10-03 21:35 UTC by GoodluckH

2022-10-03 22:28 UTC, owlot requested changes
This will only change the file in this repository, can you add it to the template file used for all repo's?
https://github.com/Arrow-air/tf-github/blob/0e06bdbd2e0ac7bca3d8f93db6e3f85a818ba8c4/src/templates/all/.cspell.config.yaml

2022-10-04 03:31 UTC, ServiceDog approved these changes

2022-10-04 16:49 UTC, ServiceDog approved these changes

2022-10-04 17:40 UTC, romanmandryk approved these changes

2022-10-04 17:48 UTC, GoodluckH commented
Someone merge this plz 
@ServiceDog @romanmandryk

2022-10-04 18:03 UTC, owlot approved these changes

2022-10-04 18:05 UTC, merged

2022-10-04 18:05 UTC, ServiceDog commented
> Someone merge this plz @ServiceDog @romanmandryk

:rofl: I got you